const SOCKET_EVENT = {
  ADD_COUNT: 'ADD_COUNT',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  ROOM_MES: 'ROOM_MES',
  CHAT: 'CHAT',
  GAME_STATUS: 'GAME_STATUS',
  COMPARED_RESULT: 'COMPARED_RESULT',
  USER_STATUS: 'USER_STATUS',
  USER_ACTION: 'USER_ACTION',
};

const GAME_STATUS_ACTION = {
  UPDATE_READY: 'UPDATE_READY',
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',
  UPDATE_ALL_USERS: 'UPDATE_ALL_USERS',
  SET_PLAYED_RESULT: 'SET_PLAYED_RESULT',
  SET_CONTINUE_GAME_SUCCESS: 'SET_CONTINUE_GAME_SUCCESS',
  SET_CONTINUE_GAME_FAIL: 'SET_CONTINUE_GAME_FAIL',
};
const PLAYED_RESULT = {
  'FAIL': 'FAIL',
  'SUCCESS': 'SUCCESS',
  'GAME_OVER': 'GAME_OVER', 
  'CONTINUED': 'CONTINUED',
};
const GAME_STATUS = {
  ...PLAYED_RESULT,
  READY: 'READY',
  START: 'START',
  CONTINUED: 'CONTINUED',
  PASS: 'PASS',
  OVER: 'OVER',
  ERROR: 'ERROR',
  ...GAME_STATUS_ACTION,
};

const USER_ACTION = {
  PLAY_CARD: 'PLAY_CARD',
  SET_READY: 'SET_READY',
  GET_ALL_PLAYERS_READY: 'GET_ALL_PLAYERS_READY',
  CONFIRM_CONTINUE_GAME: 'CONFIRM_CONTINUE_GAME',
  CONFIRM_LEAVE_GAME: 'CONFIRM_LEAVE_GAME',
};

module.exports = {
  SOCKET_EVENT,
  GAME_STATUS,
  USER_ACTION,
  PLAYED_RESULT,
  MONGO_DB_CODE: 'mongodb+srv://test-merng:4pgdgWoS1NamoYd0@cluster0.zmfzq.mongodb.net/database?retryWrites=true&w=majority',
  SECRET_KEY: 'some-secret-key',
};
