import { GameStatus } from "common-types";

export enum SOCKET_EVENT {
  ADD_COUNT = 'ADD_COUNT',
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  ROOM_MES = 'ROOM_MES',
  GAME_STATUS = 'GAME_STATUS',
  USER_ACTION = 'USER_ACTION',
  CHAT = 'CHAT',
};

export const GAME_STATUS: GameStatus = {
  READY: 'READY',
  START: 'START',
  CONTINUED: 'CONTINUED',
  PASS: 'PASS',
  OVER: 'OVER',
  ERROR: 'ERROR',

  UPDATE_READY: 'UPDATE_READY',
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',
};
export enum GameStatusTypes {
  READY = 'READY',
  START = 'START',
  CONTINUED = 'CONTINUED',
  PASS = 'PASS',
  OVER = 'OVER',
  ERROR = 'ERROR',

  UPDATE_READY = 'UPDATE_READY',
  UPDATE_ALL_USERS = 'UPDATE_ALL_USERS',
  ADD_PLAYER = 'ADD_PLAYER',
  REMOVE_PLAYER = 'REMOVE_PLAYER',

  UPDATE_LIFE = 'UPDATE_LIFE',
  SET_PLAYED_RESULT = 'SET_PLAYED_RESULT',
}

export enum USER_ACTION {
  PLAY_CARD = 'PLAY_CARD',
  SET_READY = 'SET_READY',
  GET_ALL_PLAYERS_READY = 'USER_ACTION.GET_ALL_PLAYERS_READY',
};